<?php
/** @var \TicTacToe\WebUi\View $this */
/** @var \TicTacToe\Api\ResponseBody\GameState $gameState */
$gameState = $this->get('gameState');
?>

<!doctype html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-86597034-13"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-86597034-13');
    </script>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="<?php echo $this->basePath('favicon.ico') ?>" rel="icon" />


    <link rel="stylesheet" href="<?php echo $this->basePath('assets/bootstrap.min.4.3.1.css') ?>"/>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <link rel="stylesheet" href="<?php echo $this->basePath('assets/app.css') ?>"/>

    <title>PHP Tic Tac Toe</title>
</head>
<body>
    <main id="main" role="main" class="container-fluid h-100">
        <?php echo $this->get('content') ?>
    </main>

    <?php include __DIR__ . '/_template-global-toast.phtml'; ?>

    <script>window.__INITIAL_STATE__ = <?php echo $gameState ? $gameState->toJson() : 'null'; ?></script>
    <script>window.__BASE_PATH__ = '<?php echo $this->basePath() ?>'</script>
    <script src="<?php echo $this->basePath('assets/app.js') ?>" async></script>
</body>
</html>