<?php
/** @var \TicTacToe\WebUi\View $this */
?>

<div aria-live="polite" aria-atomic="true" class="d-flex justify-content-center" style="position: absolute; top: 9vh;width: 100%;left: 0">
    <div id="global-toast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true" data-delay="10000">
        <div class="toast-header">
            <strong id="global-toast-title" class="mr-auto"></strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div id="global-toast-body" class="toast-body bg-white"></div>
    </div>
</div>