<?php
/** @var \TicTacToe\WebUi\View $this */
?>

<div id="global-toast-wrapper" class="d-flex justify-content-center d-none" style="position: absolute; top: 9vh;width: 100%;left: 0">
    <div id="global-toast" class="toast fade">
        <div class="toast-header">
            <strong id="global-toast-title" class="mr-auto"></strong>
            <button type="button" class="ml-2 mb-1 close" id="global-toast-close-button">
                <span>&times;</span>
            </button>
        </div>
        <div id="global-toast-body" class="toast-body bg-white"></div>
    </div>
</div>